### ISSUE TITLE
Restrict Plates, Not Just Armor

### ISSUE THREAD

**Issue by PhantomInTime** [VforValens/Progression#10]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when PMC's at starting traders almost always have Class IV-VI plates.

**Describe the solution you'd like**
Plates follow the same trader restrictions save for the very rare and occasional low level Class IV-VI plate.

**Describe alternatives you've considered**
Not using this mod lmao

**Comment by VforValens** [comment]
Duplicate of https://github.com/VforValens/Progression/issues/9 
Planned but no timeline for implementation.
