### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Midnight1588** [VforValens/Progression#11]
**Describe the bug**
Game crashes after about 15-25 min in raid

**To Reproduce**
Ive played a few raids with the mod installed and it would crash everytime. I would then remove the mod and I am able to play with no crashes

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 3.8 of SPT

![Screenshot 2024-04-08 151520](https://github.com/VforValens/Progression/assets/166444387/0e11f6e8-ae59-4e2b-aac8-b72775608c39)

**Comment by VforValens** [comment]
This is unfortunately a mod conflict rather than anything specifically wrong with Progression. You will need to figure out which mod(s) are conflicting with mine or simply forego the Progression mod.

**Comment by Midnight1588** [comment]
OK thank you!
