### ISSUE TITLE
Attachments not following same rules as weapons and equipment..

### ISSUE THREAD

**Issue by RedMamba28** [VforValens/Progression#12]
**Describe the bug**
I've noticed after killing pmcs that the attachments that spawn on they're gear don't follow the same rules as the gear and equipment itself. Ive killed to pmcs now (One level 9, one level 17) with high tier thermals on theyre weapons

**To Reproduce**
Kill pmcs and inspect they're gear.

**Expected behavior**
Attachments falling in line with the expected trader level.

**Screenshots**

**Desktop (please complete the following information):**
On 3.8.0

**Comment by RedMamba28** [comment]
Side Note:

I havent updated to version 2.01 but wasn't sure if this issue falls under the post level 14 changes made with that update.

**Comment by VforValens** [comment]
Attachments are a feature that may, or may not, come later down the road. It requires a hefty amount of code commitment as it isn't anywhere near as easy as the current implementation as to how attachments are handled; which is randomized.
