### ISSUE TITLE
PMCs do not have unloading

### ISSUE THREAD

**Issue by EvilUbi** [VforValens/Progression#14]
I only use your mod to change the PMCs

![2024-04-17 19-06 _-83 3, 11 9, -550 8_0 2, 0 8, -0 5, 0 3_8 80 (0)](https://github.com/VforValens/Progression/assets/113224069/643be31d-cb1e-4d93-b87b-afac37ceb209)

![2024-04-17 19-27 _381 4, -15 0, 257 5_0 0, 1 0, -0 1, 0 1_11 18 (0)](https://github.com/VforValens/Progression/assets/113224069/2aaebb7b-3c3a-48a2-bae1-93466654fb66)

**Comment by VforValens** [comment]
I'm gonna need way more detail. What do you mean "they don't have
unloading"???
