### ISSUE TITLE
Please add a pmc squad feature that goes well with the progression system

### ISSUE THREAD

**Issue by Somedood21** [VforValens/Progression#15]
**Is your feature request related to a problem? Please describe.**
NA
**Describe the solution you'd like**
NA
**Describe alternatives you've considered**
NA
**Additional context**
I have been using SWAG donuts for the pmc squad fight experience, but I realise the pmc squad loadouts are mainly starting out pmcs and there is no mod that solves this except for realism mod. However realism gun mods have been too obvious so I prefer yours more. Therefore I was hoping you could add a feature/mod that customises pmcs to spawn in squads, with the progression mod system added to them.

**Comment by VforValens** [comment]
You could always use Realism, disable it's progression system, and substitute in mine. Unfortunately I don't think that is something I'll ever take up on my own as I just don't have the time.
