### ISSUE TITLE
"Required slot" ... "was generated incorrectly, falling back to weapon preset" errors

### ISSUE THREAD

**Issue by SimpleARUser** [VforValens/Progression#16]
When spawning bots the server generates error message like the following. This happens many times and only happens after instalation of Valens. - 

Sample error below - 

[Client Request] /client/game/bot/generate
Required slot 'mod_reciever' on weapon_izhmeh_pm_treaded_9x18pm Holster was empty on sptusec
Weapon 579204f224597773d619e051 weapon_izhmeh_pm_treaded_9x18pm was generated incorrectly, falling back to weapon preset see error above
Required slot 'mod_reciever' on weapon_izhmeh_pm_treaded_9x18pm Holster was empty on sptusec
Weapon 579204f224597773d619e051 weapon_izhmeh_pm_treaded_9x18pm was generated incorrectly, falling back to weapon preset see error above
[Client Request] /client/game/bot/generate

**Comment by VforValens** [comment]
Isn't game breaking and happens even in SPT when a weapon is generated incorrectly albeit rarer.
