### ISSUE TITLE
Bot loadouts

### ISSUE THREAD

**Issue by Midnight1588** [VforValens/Progression#17]
**Describe the bug**
So this isn't necessarily a bug but I noticed with the newest update PMCs very rarely have any sort of optic or scope on their guns. This might be intended or those PMCs just got extremely unlucky lol idk just seemed odd

**Comment by Midnight1588** [comment]
I think im Lvl 29

**Comment by Midnight1588** [comment]
Im lvl 31 actually sry

**Comment by VforValens** [comment]
Ok. Is this every bot? What are we talking about here? Have any screenshots?

**Comment by Midnight1588** [comment]
I didnt grab any screen shots sry. But i killed 7 pmcs and 5 of them had no optic on their gun

**Comment by VforValens** [comment]
Going to have to deal with it for now until I can get some communication from Chomp as to how the modslots work as there's no documentation for them currently.

**Comment by Midnight1588** [comment]
Ok cool. Yea not a huge deal just wasn't sure if it was intended or not
