### ISSUE TITLE
Full Rigs

### ISSUE THREAD

**Issue by Midnight1588** [VforValens/Progression#18]
So this isnt a bug at all just curious if its intended for PMC's to have completely full Rigs? I noticed every PMC i killed every slot was filled with multiple mags for both guns and multiple meds. I am Lvl 41 so that would kinda make sense just wasnt sure. Either way im seeing Great variety!!

**Comment by VforValens** [comment]
Yes, intended currently. May adjust so that they don't have so much loot, we'll see.
