### ISSUE TITLE
PMCs carrying Boss Face Masks

### ISSUE THREAD

**Issue by dingodrum** [VforValens/Progression#19]
The 'problem' is in the title. We're seeing a lot of PMCs carrying bosses masks. - Not something that's out of the question, but I think we should be seeing a lot less regularly. - We had a raid last night, wherein 4 of us (on the fika mod) all had managed to gain a boss mask each for bosses that, according to the server, weren't spawned

**Describe the solution you'd like**
Reduced Masks on PMCs

**Describe alternatives you've considered**
Changing spawn chances of bosses to ensure PMCs aren't looting. It doesn't appear to make a difference.

**Comment by VforValens** [comment]
This is indeed an intended feature. Unfortunately there's only so few face masks that are truly even worth wearing.

It's also not about whether or not the boss is on the map but to simulate the fact that you can absolutely farm bosses during the wipe and bring in their gear. 

Additionally Tagilla's face mask is easily one of the best in the game. Currently, most equipment has the same weighting (chance) to spawn which is set at 10. There will be a balance pass eventually but that's low priority right now in comparison to getting the entire mod refactored for easier readability and to be more performant.
