### ISSUE TITLE
Server Console error/ No bots spawn with Progression mod 1.4.2 update

### ISSUE THREAD

**Issue by DickenCiderz** [VforValens/Progression#2]
**Describe the bug**
Most recent update to your progression mod, gives me a server console error, and no bots spawn. Previous release, 1.4.1, does not have the issue. Seems like the map doesn't make a difference. It does it will all maps. Even tried on a fresh install and only the progression mod, and same error.

**To Reproduce**
1. Install mod
2. Launch game
3. Start raid and wait a few seconds..

**Expected behavior**
Bots should spawn.

**Screenshots**
See screenshot of error.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Version [Most recent update. lol ]

**Additional context**
I haven't tried without other mods yet, but the previous version of the mod, 1.4.1, works fine with no issues with all the mods I have installed ATM.
![errormessage](https://user-images.githubusercontent.com/131814942/234388853-096c4bcc-cbc5-4ff2-b321-9812925c7f4e.png)

**Comment by NisseAqq** [comment]
Is this fixed or is it being worked on? Does the same for me.

**Comment by Killer8me** [comment]
same issue with most recent version but only upon hitting roughly level 15, other issue post has same issue as me it seems but this one is more in-depth so posting here
