### ISSUE TITLE
1.6.0 bot gen errors

### ISSUE THREAD

**Issue by MusicManiac** [VforValens/Progression#6]
Console is severely spammed by botgen errors

**To Reproduce**
Load into the raid wait for bots to start spawning

**Expected behavior**
No errors

**Additional context**
Rolling back to 1.5.1 removes the errors so it's something to do with latest update.
[server-2024-01-14.log](https://github.com/VforValens/Progression/files/13930110/server-2024-01-14.log)

**Comment by Sensokaku** [comment]
happening to me as well with the same type of errors

**Comment by VforValens** [comment]
Resolved if you install 0.14 content mod or roll back to previous version that doesn't include the 0.14 content
Mod description updated to notate that the mod is required with a link to the mod.
Mod here: https://hub.sp-tarkov.com/files/file/1683-14-0-content-preview-guns-gear-ammo-and-attachments-added/
