### ISSUE TITLE
Bunch of errors in console 

### ISSUE THREAD

**Issue by PureRussianVodka** [VforValens/Progression#7]
**Describe the bug**
an insanely large amount of red text

**To Reproduce**
1. start a raid
2. look in console
3. see a bunch of red text
4. notice pmcs not spawning in raid

**Screenshots**
https://cdn.discordapp.com/attachments/1204894394713640960/1204914349911711744/image.png?ex=65d676ef&is=65c401ef&hm=cffcdfde54916542b7810a062ba8e8424c9cfdf1ff61ddbcdeaa645716853e29&

https://cdn.discordapp.com/attachments/1204894394713640960/1204894395065966662/Screenshot_69.png?ex=65d66459&is=65c3ef59&hm=8003c0f5e7f14c0512f84f79881966732f501026921e794af48e996f61904582&

**Comment by Jordan0204b** [comment]
I'm having issues with this same exact thing!!! Please someone get a fix going.

**Comment by MusicManiac** [comment]
Same as https://github.com/VforValens/Progression/issues/6
